/**
 * One page's worth of this app, as data somebody else's site can read.
 *
 *   npm run press-kit
 *
 * Output: marketing/press-kit/, an `index.json` and a handful of web sized
 * images.
 *
 * The app has a page on moox.io, and that page is now three things at once: the
 * pitch, the link to both stores, and the privacy policy, because the privacy
 * URL both stores were given points at it. Writing those three by hand, in a
 * second repository, is how a page ends up describing the app as it was two
 * versions ago.
 *
 * So this repository publishes and that site consumes. `marketing/listing.json`
 * is already the single source for the App Store and for Play; the page becomes
 * its third reader rather than a fourth copy. `marketing/privacy.md` is the
 * policy, written from what the code does. The images come from the deck that
 * was already composed and looked at.
 *
 * **Web sized, not store sized.** A store screenshot is 1320 x 2868 and two
 * megabytes, and a page that loads five of those is a page nobody waits for.
 * These are 720 wide and JPEG, which is a few hundred kilobytes for the set,
 * and it is why the whole kit can live on a branch instead of in a bucket.
 */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.join(__dirname, "..", "..");
const OUT = path.join(ROOT, "marketing", "press-kit");
const SHOTS = path.join(ROOT, "marketing", "renders", "app-store");
// Which locale the images come from. The page is in one language; the copy for
// the others travels with the kit so a translated page is a template change
// rather than another generator.
const SHOT_LOCALE = process.env.HTN_PRESS_LOCALE || "en-US";
const SHOT_WIDTH = process.env.HTN_PRESS_WIDTH || "720";
const SHOT_COUNT = Number(process.env.HTN_PRESS_SHOTS || 5);

// ImageMagick 7 renamed the entry point and both are in the wild.
const MAGICK = ["magick", "convert"].find((bin) => {
  try {
    execFileSync(bin, ["-version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
});

function fail(message, hint) {
  console.error(`\n  ${message}\n`);
  if (hint) console.error(`  ${hint}\n`);
  process.exit(1);
}

if (!MAGICK) {
  fail(
    "This needs ImageMagick to resize the screenshots.",
    "brew install imagemagick, or apt install imagemagick.",
  );
}

const listing = JSON.parse(fs.readFileSync(path.join(ROOT, "marketing", "listing.json"), "utf8"));
const privacyPath = path.join(ROOT, "marketing", "privacy.md");
if (!fs.existsSync(privacyPath)) {
  fail("No marketing/privacy.md, and the app page is the privacy policy.");
}

const from = path.join(SHOTS, SHOT_LOCALE);
if (!fs.existsSync(from)) {
  fail(
    `No deck at marketing/renders/app-store/${SHOT_LOCALE}.`,
    "npm run deck composes it, npm run deck:fetch brings one down from CI.",
  );
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(path.join(OUT, "shots"), { recursive: true });

// The shots, in the order the deck puts them, which is the order they were
// written to be read in.
const sources = fs
  .readdirSync(from)
  .filter((name) => name.endsWith(".png"))
  .sort()
  .slice(0, SHOT_COUNT);

const shots = sources.map((name, i) => {
  const out = `${String(i + 1).padStart(2, "0")}.jpg`;
  execFileSync(MAGICK, [
    path.join(from, name),
    "-resize",
    `${SHOT_WIDTH}x`,
    "-quality",
    "82",
    "-strip",
    path.join(OUT, "shots", out),
  ]);
  return `shots/${out}`;
});

// The icon, at a size a page uses rather than at the size a store demands.
execFileSync(MAGICK, [
  path.join(ROOT, "assets", "icon.png"),
  "-resize",
  "256x256",
  "-strip",
  path.join(OUT, "icon.png"),
]);

const kit = {
  "//":
    "Generated by tools/marketing/press-kit.cjs from marketing/listing.json, " +
    "marketing/privacy.md and the composed deck. Do not edit: it is replaced " +
    "on every run. Paths are relative to this file.",
  slug: "hide-the-notch",
  generated: new Date().toISOString().slice(0, 10),
  urls: listing.urls,
  icon: "icon.png",
  shots,
  shotLocale: SHOT_LOCALE,
  privacy: fs.readFileSync(privacyPath, "utf8"),
  locales: Object.fromEntries(
    Object.entries(listing.locales).map(([locale, copy]) => [
      locale,
      {
        name: copy.name,
        subtitle: copy.subtitle,
        short: copy.short,
        description: copy.description,
      },
    ]),
  ),
};

fs.writeFileSync(path.join(OUT, "index.json"), `${JSON.stringify(kit, null, 2)}\n`);

const bytes = fs
  .readdirSync(path.join(OUT, "shots"))
  .reduce((n, f) => n + fs.statSync(path.join(OUT, "shots", f)).size, 0);

console.log("");
console.log(`  ${shots.length} shots from ${SHOT_LOCALE}, ${SHOT_WIDTH}px wide`);
console.log(`  ${Object.keys(kit.locales).length} locales of copy`);
console.log(`  ${(bytes / 1024).toFixed(0)} kB of images`);
console.log("");
console.log(`  marketing/press-kit/index.json`);
console.log("");
