const { withGradleProperties } = require("expo/config-plugins");

/**
 * Gives the Gradle daemon enough metaspace to finish a release build.
 *
 * Prebuild writes `-Xmx2048m -XX:MaxMetaspaceSize=512m`, and 512 MiB is not
 * enough for this project. Gradle says so out loud on a laptop, where the
 * daemon survives the build and expires afterwards:
 *
 *   The Daemon will expire after the build after running out of JVM Metaspace.
 *   The project memory settings are likely not configured or are configured to
 *   an insufficient value.
 *
 * On a GitHub runner it does not survive. `lintVitalAnalyzeRelease` loads a jar
 * of custom lint checks per module, throws `OutOfMemoryError: Metaspace` while
 * verifying their bytecode, and the daemon then spends the rest of the hour
 * failing to allocate anything at all, one `RMI TCP Connection` exception at a
 * time, until the job hits its timeout. Nothing in the log says "out of
 * memory" where a person would look for it: the build simply stops printing
 * tasks, forty seven minutes before it is killed, which is why this took a run
 * and a log read to find rather than a glance.
 *
 * A gigabyte of metaspace and four of heap. Both fit a hosted runner, which has
 * sixteen, and neither is a number a laptop notices.
 *
 * `android/` is regenerated by every prebuild, so this is a plugin.
 */
const KEY = "org.gradle.jvmargs";
const VALUE = "-Xmx4096m -XX:MaxMetaspaceSize=1024m";

module.exports = (config) =>
  withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find((item) => item.type === "property" && item.key === KEY);
    if (existing) {
      existing.value = VALUE;
    } else {
      cfg.modResults.push({ type: "property", key: KEY, value: VALUE });
    }
    return cfg;
  });
