const { withProjectBuildGradle } = require("expo/config-plugins");

/**
 * Stops the Android build hanging on a repository that had nothing to say.
 *
 * `expo-updates` depends on `org.bouncycastle:bcutil-jdk15to18:1.81`, which
 * asks for `bcprov-jdk15to18:[1.81,1.82)`. A *range* is the whole problem: to
 * pick the highest version that fits, Gradle has to **list** the versions in
 * every declared repository rather than stopping at the first that answers. One
 * of ours is jitpack, which serves source built GitHub artefacts and nothing
 * else, so the question is meaningless there. When jitpack is slow the answer
 * never comes, the read times out, and five minutes of build dies on it. Three
 * times in a row here.
 *
 * Two fixes, because they cure different things.
 *
 * The **forced version** removes the range. `bcutil` 1.81 wants any 1.81.x, so
 * 1.81 satisfies it exactly, and a fixed version is fetched straight from the
 * repository that has it instead of being searched for in all of them. This is
 * the one that makes the build stop depending on jitpack's mood.
 *
 * The **content filter** says what jitpack is for. That is not a workaround for
 * a slow server, it is a true statement about what that repository holds, and
 * it means the next dynamic version anybody introduces does not have to learn
 * this lesson again. It is applied through `repositories.all`, a live hook,
 * rather than by editing the one declaration in this file: Expo's own gradle
 * plugin adds jitpack to each module too, which is why editing the root
 * declaration alone changed nothing.
 *
 * `android/` is regenerated by every prebuild, so this is a plugin.
 */
const BLOCK = `
// Added by plugins/withJitpackScope.cjs, see that file for why.
allprojects {
  repositories {
    all { repo ->
      if (repo instanceof MavenArtifactRepository && repo.url.toString().contains('jitpack')) {
        repo.content {
          includeGroupByRegex 'com\\\\.github\\\\..*'
          includeGroupByRegex 'com\\\\.gitlab\\\\..*'
          includeGroupByRegex 'org\\\\.bitbucket\\\\..*'
        }
      }
    }
  }
  configurations.all {
    resolutionStrategy {
      force 'org.bouncycastle:bcprov-jdk15to18:1.81'
    }
  }
}
`;

const MARKER = "withJitpackScope";

module.exports = function withJitpackScope(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error("withJitpackScope expects a Groovy build.gradle");
    }
    if (!cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents += BLOCK;
    }
    return cfg;
  });
};
