/**
 * Lets the release lane decide the Android version code, from the environment.
 *
 * A version code is spent for the whole package, forever, so the only place
 * that knows the next free one is Play itself. `fastlane android beta` asks it,
 * which means the number arrives at build time and cannot be written down in
 * `app.json`. Without this plugin there is nowhere to put it: `app.json` is
 * static JSON, so it cannot read an environment variable, and prebuild writes
 * `versionCode 1` into `android/app/build.gradle` from the value it does not
 * find there.
 *
 * The lane used to pass `-Pandroid.injected.version.code` to gradle instead.
 * That silently does nothing here: the property is an old AGP affordance, the
 * merged manifest came out `android:versionCode="1"` all the same, and Play
 * refused the upload after a four minute build with "Version code 1 has
 * already been used". Silently, which is the expensive part. So the number is
 * put where prebuild reads it, and `build_aab!` checks the generated gradle
 * file before spending the four minutes.
 *
 * Unset, the config is left exactly as it was, which is what every development
 * build wants: `npx expo run:android` has no business asking Play anything.
 *
 * `android/` is regenerated by every prebuild, so this is a plugin.
 */
module.exports = (config) => {
  const raw = (process.env.ANDROID_VERSION_CODE || "").trim();
  if (raw === "") return config;

  const code = Number(raw);
  if (!Number.isInteger(code) || code < 1) {
    throw new Error(`ANDROID_VERSION_CODE must be a positive whole number, got "${raw}".`);
  }

  return { ...config, android: { ...config.android, versionCode: code } };
};
