# A list of devices you want to take the screenshots from
devices([
  "iPhone X",
  "iPhone 8 Plus",
  "iPad Pro (12.9-inch)",
#   "iPad Pro (9.7-inch)",
#   "Apple TV 1080p"
])

languages([
  "en-US",
  # "fr-FR",
  # "de-DE",
  # "it-IT",
  # ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

scheme "HideTheNotch"
project "./ios/HideTheNotch.xcodeproj"
# workspace "./Project.xcworkspace"

# output_directory "./screenshots"

clear_previous_screenshots true