# https://docs.fastlane.tools/actions/

fastlane_version "2.64.0"

default_platform :ios

platform :ios do
  before_all do
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cert
    sigh
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(
      scheme: JSON.parse(IO.read("../../app.json"))["name"],
    )
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    cert
    sigh
    # match(type: "appstore")
    # snapshot
    # frameit
    
    version = JSON.parse(IO.read("../../package.json"))["version"]
    scheme = JSON.parse(IO.read("../../app.json"))["name"]
    xcodeproj = "./#{scheme}.xcodeproj"

    increment_build_number
    increment_version_number(
      version_number: version,
    )
    
    gym(
      scheme: scheme,
    )
    
    deliver
    
    commit_version_bump(
      xcodeproj: xcodeproj,
      message: version,
      include: %w[package.json]
    )
    add_git_tag(
      tag: "v#{version}",
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
